### ISSUE TITLE
[CLI]Pantalla configuración de perfil

### ISSUE THREAD

**Issue by matiduarte** [matiduarte/taller2-mensajeroX#18]

**Comment by juanmabaracat** [comment]
Pantalla que muestra el perfil de un contacto en particular.

**Comment by juanmabaracat** [comment]
Pantalla que permite editar el perfil del usuario.

**Comment by matiduarte** [comment]
Corregir:
1 - Cuando se presiona el boton guardar debe regresar a la pantalla de logeo.
2 - Teclado no desaparece despues de ingresar el nombre
3 - Sacar Hint con el nombre del usuario
