### ISSUE TITLE
[CLI] Mejorar usabilidad pantalla principal

### ISSUE THREAD

**Issue by gfusca** [matiduarte/taller2-mensajeroX#25]
Perfil e información es confuso
La información de la aplicación no es tan importante como para que aparezca en la pantalla principal

**Comment by matiduarte** [comment]
Esa pantalla no va a quedar ahí.
Aparece después de la pantalla de registro solo porque uno de los integrantes la esta haciendo y para no andar tocando el manifest todo el tiempo se engancho después de la pantalla registro.
