### ISSUE TITLE
[CLI][SVR]Implementar localizacion

### ISSUE THREAD

**Issue by quimeyfunes** [matiduarte/taller2-mensajeroX#37]
Mostrar una localización en en el radio en el que se encuentra el usuario.

**Comment by juanmabaracat** [comment]
**Alcance:**
- _Servidor:_
  - Se agregó el servicio de Check-In que le permite conocer al cliente donde se encuentra.
- _Cliente:_
  - Se agregó el servicio que le permite al usuario hacer el check-in.
  - Se muestra la ubicación del usuario en su pantalla de perfil.
  - Se muestra la ubicación del contacto en su pantalla de información.
  - Se muestra la ubicación para cada usuario en la pantalla lista de contactos.
